name: Hola Mundo 
on:  
  push: 
    branches: 
    - master
jobs:  
  hola_mundo:    
    name: Hola mundo con github actions  
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v1
    - run: echo "Hola"
